version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/ui"  
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/icons"  
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/colors" 
    schedule:
      interval: "daily"