nodeLinker: pnp
pnpMode: loose
enableGlobalCache: false
enableHardenedMode: false

compressionLevel: 4
enableMirror: false

npmPublishRegistry: 'https://registry.npmjs.org'
npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  "@esbuild/linux-x64":
    dependencies:
      esbuild: "*"
  "@rollup/rollup-linux-x64-gnu":
    dependencies:
      rollup: "*"
  "turbo-linux-64":
    dependencies:
      turbo: "*"
  'tailwind-merge@*':
    peerDependencies:
      typescript: '*'
  'clsx@*':
    peerDependencies:
      typescript: '*'
  typescript@*:
    peerDependencies:
      '@types/node': '*'
    dependencies:
      tslib: '*'
  '@zagdang/ui@*':
    peerDependencies:
      typescript: '*'
  '@zagdang/icons@*':
    peerDependencies:
      typescript: '*'
  '@zagdang/colors@*':
    peerDependencies:
      typescript: '*'
