nodeLinker: pnp
pnpMode: strict
enableGlobalCache: false
enableHardenedMode: false

compressionLevel: 0  # 더 빠른 압축
enableMirror: true  # 미러 캐시 활성화

npmPublishRegistry: 'https://registry.npmjs.org'
npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  "@esbuild/linux-x64@*":
    supportedArchitectures:
      - os: "linux"
        cpu: "x64"
  "@rollup/rollup-linux-x64-gnu@*":
    supportedArchitectures:
      - os: "linux"
        cpu: "x64"
  "turbo-linux-64@*":
    supportedArchitectures:
      - os: "linux"
        cpu: "x64"
  'tailwind-merge@*':
    peerDependencies:
      typescript: '*'
  'clsx@*':
    peerDependencies:
      typescript: '*'
  typescript@*:
    peerDependencies:
      '@types/node': '*'
    dependencies:
      tslib: '*'
  '@zagdang/ui@*':
    peerDependencies:
      typescript: '*'
  '@zagdang/icons@*':
    peerDependencies:
      typescript: '*'
  '@zagdang/colors@*':
    peerDependencies:
      typescript: '*'
