nodeLinker: pnp
pnpMode: loose
enableGlobalCache: false
enableHardenedMode: false

compressionLevel: 0
enableMirror: false

npmPublishRegistry: 'https://registry.npmjs.org'
npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  'debug@*':
    peerDependencies:
      'supports-color': '*'
  'chromatic@*':
    peerDependencies:
      'esprima': '*'
  '@storybook/core@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
      '@types/react': '*'
  'tailwind-merge@*':
    peerDependencies:
      typescript: '*'
  'clsx@*':
    peerDependencies:
      typescript: '*'
  'class-variance-authority@*':
    peerDependencies:
      typescript: '*'
  'eslint-plugin-storybook@*':
    peerDependencies:
      typescript: '*'
  'rollup@*':
    peerDependencies:
      'source-map-support': '*'
  '@types/node@*':
    peerDependencies:
      'punycode': '*'
      'util': '*'
  '@types/react-dom@*':
    peerDependencies:
      'react': '*'
  'vite-plugin-svgr@*':
    peerDependencies:
      'react': '*'
      '@types/react': '*'
  '@testing-library/jest-dom@*':
    peerDependencies:
      '@types/aria-query': '*'
  typescript@*:
    peerDependencies:
      '@types/node': '*'
    dependencies:
      tslib: '*'
  '@zagdang/ui@*':
    peerDependencies:
      typescript: '*'
      react: '*'
      '@types/react': '*'
  '@zagdang/icons@*':
    peerDependencies:
      typescript: '*'
      react: '*'
      '@types/react': '*'
  '@zagdang/colors@*':
    peerDependencies:
      typescript: '*'
