name: CI

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #     - ci/ci-pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    if: ${{ github.actor != 'l10nbot' }} # Avoid running for 'l10nbot'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Enable Corepack (for Yarn 2)
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate
      
          
      - name: Cache Yarn dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-
              
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
      
      - name: Install TurboRepo
        run: yarn add turbo --dev

  lint:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack (for Yarn 2)
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate

      - name: Restore Yarn cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Prettier check
        run: yarn format --check

      - name: Lint
        run: yarn lint

  test:
    needs: [install-dependencies, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack (for Yarn 2)
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate

      - name: Restore Yarn cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-
          
      - name: Install dependencies
        run: yarn install --immutable
          
      - name: Run tests
        run: yarn turbo run test --filter=@zagdang/ui -- --runInBand --ci --coverage

      - name: Check for coverage summary
        run: |
          if [ ! -f packages/ui/coverage/coverage-summary.json ]; then
            echo "coverage-summary.json not found!"
            exit 1
          fi

      - name: Get Coverage Info
        id: coverage
        run: |
          COVERAGE_REPORT=$(cat coverage/coverage-summary.json)
          echo "statements=$(echo $COVERAGE_REPORT | jq -r '.total.statements.pct')" >> $GITHUB_OUTPUT
          echo "branches=$(echo $COVERAGE_REPORT | jq -r '.total.branches.pct')" >> $GITHUB_OUTPUT
          echo "functions=$(echo $COVERAGE_REPORT | jq -r '.total.functions.pct')" >> $GITHUB_OUTPUT
          echo "lines=$(echo $COVERAGE_REPORT | jq -r '.total.lines.pct')" >> $GITHUB_OUTPUT

      - name: Comment PR with Coverage
        uses: thollander/actions-comment-pull-request@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ## Test Coverage Report 📊
            - Statements: ${{ steps.coverage.outputs.statements }}%
            - Branches: ${{ steps.coverage.outputs.branches }}%
            - Functions: ${{ steps.coverage.outputs.functions }}%
            - Lines: ${{ steps.coverage.outputs.lines }}%

  build:
    needs: [install-dependencies, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore Yarn cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-
          
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: |
          yarn turbo build --parallel
        env:
          NODE_OPTIONS: --max-old-space-size=4096

  storybook-build:
    needs: [install-dependencies, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Yarn cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-
          
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Storybook
        run: yarn turbo run build-storybook

  required:
    needs: [install-dependencies, lint, build, storybook-build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
