name: CI

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #     - ci/ci-pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    if: ${{ github.actor != 'l10nbot' }} # Avoid running for 'l10nbot'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Enable Corepack (for Yarn 2)
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate
      
          
      - name: Cache Yarn dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-
              
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
      
      - name: Install TurboRepo
        run: yarn add turbo --dev

  lint-and-test:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack (for Yarn 2)
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate

      - name: Restore Yarn cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Prettier check
        run: yarn format --check

      - name: Lint
        run: yarn lint
      
      - name: Run tests
        run: yarn turbo run test --filter=@zagdang/ui -- --runInBand --ci

  build:
    needs: [install-dependencies, lint-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack (for Yarn 2)
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate
      
      - name: Restore Yarn cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-
          
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: |
          yarn turbo build --parallel
        env:
          NODE_OPTIONS: --max-old-space-size=4096

  storybook-build:
    needs: [install-dependencies, lint-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack (for Yarn 2)
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate

      - name: Restore Yarn cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.*
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-
          
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Storybook
        run: yarn turbo run build-storybook

  required:
    needs: [install-dependencies, lint-and-test, build, storybook-build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
